exports.routes = [
    { method : "get",  url : "/mapp_account_check",     module : "mapp_account_check",     action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_binding_request",   module : "mapp_binding_request",   action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_binding_confirm",   module : "mapp_binding_confirm",   action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_role_info",         module : "mapp_role_info",         action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_account_status",    module : "mapp_account_status",    action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_lock_account",      module : "mapp_lock_account",      action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_unlock_account",    module : "mapp_unlock_account",    action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_unbinding_request", module : "mapp_unbinding_request", action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_modify_password",   module : "mapp_modify_password",   action : "action", use_session : 0 },
    { method : "get",  url : "/mapp_offline_account",   module : "mapp_offline_account",   action : "action", use_session : 0 },
    { method : "post", url : "/notify_remote_login",    module : "notify_remote_login",    action : "action", use_session : 0 },
    { method : "get",  url : "/kf_lock_request",        module : "kf_lock_request",        action : "action", use_session : 0 },
    { method : "get",  url : "/kf_lock_confirm",        module : "kf_lock_confirm",        action : "action", use_session : 0 },
    { method : "get",  url : "/kf_unlock_request",      module : "kf_unlock_request",      action : "action", use_session : 0 },
    { method : "get",  url : "/kf_unlock_confirm",      module : "kf_unlock_confirm",      action : "action", use_session : 0 },
    { method : "get",  url : "/my_ip",                  module : "my_ip",                  action : "action", use_session : 0 },
    //login
    { method : "get",  url : "/syyx_login/nycs/get_captcha",      module : "syyx_login/nycs/get_captcha",        action : "action", use_session : 1 },
    { method : "get",  url : "/syyx_login/nycs/check_captcha",    module : "syyx_login/nycs/check_captcha",        action : "action", use_session : 1 },
    { method : "post",  url : "/syyx_login/nycs/login",           module : "syyx_login/nycs/login",               action : "action", use_session : 1 },
    { method : "get",  url : "/syyx_login/nycs/check_user_login", module : "syyx_login/nycs/check_user_login",      action : "action", use_session : 0 },
    { method : "get",  url : "/syyx_login/nycs/login_out",        module : "syyx_login/nycs/login_out",            action : "action", use_session : 0 },
]