//config_remote_server_url------------------------------------------
var remote_server_url_list = {
    check_account         : '/Ajax/Reg/account_check.aspx',
    check_idcard          : '/Ajax/Reg/check_idcard.aspx',
    check_captcha         : '/Ajax/Reg/check_captcha.aspx',
    register_account      : '/Ajax/Reg/register_account.aspx',
    get_captcha           : '/Ajax/Reg/captcha.aspx',
    active_gift           : 'http://activity.syyx.com/nycs_activate/activate_giftbag.shtml',

    get_news_info         : 'http://nycs.syyx.com/ajax/news/getnewsinfo.aspx',
    get_vote_info         : 'http://nycs.syyx.com/ajax/news/GetNewsVote.aspx',
    vote                  : 'http://nycs.syyx.com/ajax/news/vote.aspx',
    get_related_news      : 'http://nycs.syyx.com/ajax/news/GetRelatedNews.aspx',
    get_3rd_download_list : 'http://nycs.syyx.com/ajax/download/get17173.aspx',
    get_patch_info_list   : 'http://nycs.syyx.com/ajax/download/GetPatchInfoList.aspx',
    get_download_tools    : 'http://nycs.syyx.com/ajax/download/GetToolsDownload.aspx',
    get_news_list         : 'http://nycs.syyx.com/ajax/news/getnewslist.aspx',
    get_download_client   : 'http://nycs.syyx.com/ajax/download/getclientinfo.aspx',
    get_goods_list        : 'http://nycs.syyx.com/ajax/gameinfo/getgoodslist.aspx',
    get_data_class        : 'http://nycs.syyx.com/ajax/gameinfo/getdataclass.aspx',
    get_task_class        : 'http://nycs.syyx.com/ajax/gameinfo/gettaskclass.aspx',
    get_task_list         : 'http://nycs.syyx.com/ajax/gameinfo/gettasklist.aspx',
    get_task_info         : 'http://nycs.syyx.com/ajax/gameinfo/gettaskinfo.aspx',
    get_armint_list       : 'http://nycs.syyx.com/ajax/Metier/MetierArming.aspx',
    get_map_monster       : 'http://nycs.syyx.com/ajax/gameinfo/getmonster.aspx',
    get_map_task          : 'http://nycs.syyx.com/ajax/gameinfo/getmaptask.aspx',
    get_map_npc           : 'http://nycs.syyx.com/ajax/gameinfo/getmapnpc.aspx',
    get_serach_game_lib   : 'http://nycs.syyx.com/ajax/gameinfo/getsearch.aspx',
    get_user_pic_list     : 'http://nycs.syyx.com/Ajax/Pic/GetUserPicList.aspx',
    get_game_pic_list     : 'http://nycs.syyx.com/Ajax/Pic/GetGamePicList.aspx',

    game_lib_goods        : '/game_lib_content.html',
    game_lib_info         : '/game_lib_content_1.html',
    game_lib_task         : '/game_lib_content_2.html',
    game_lib_map_monster  : '/game_lib_content_3.html',
    game_lib_map_npc      : '/game_lib_content_4.html',
    game_lib_map_task     : '/game_lib_content_5.html',
    serach_game_lib       : '/game_lib_search.html',

    news_content          : '/news_content.html',
    news_list             : '/news_list.html',

    recommend_server        : 'http://att.syyx.com/XGame/StaticHtml/2.htm',
    index_top_news          : 'http://att.syyx.com/XGame/StaticHtml/20.htm',
    index_slider_news       : 'http://att.syyx.com/xgame/PicLink/piclink1.htm',
    index_news_list         : 'http://att.syyx.com/XGame/StaticHtml/27.htm',
    index_images_ad         : 'http://att.syyx.com/xgame/PicLink/piclink2.htm',
    index_game_lib_summary  : 'http://att.syyx.com/XGame/StaticHtml/18.htm',
    index_game_feature      : 'http://att.syyx.com/XGame/StaticHtml/19.htm',
    index_user_center       : 'http://att.syyx.com/XGame/StaticHtml/17.htm',
    index_game_pic          : 'http://att.syyx.com/XGame/StaticHtml/16.htm',
    index_game_video        : 'http://att.syyx.com/XGame/StaticHtml/15.htm',
    index_iframe_link       : 'http://att.syyx.com/XGame/StaticHtml/14.htm',
    index_media_img         : 'http://att.syyx.com/XGame/StaticHtml/13.htm',
    index_link              : 'http://att.syyx.com/XGame/StaticHtml/21.htm',
    news_activity           : 'http://att.syyx.com/XGame/StaticHtml/4.htm',
    news_related_img        : 'http://att.syyx.com/XGame/StaticHtml/3.htm',
    index_news_list_1       : 'http://att.syyx.com/news/js/topnews/0/1.htm',
    index_news_list_2       : 'http://att.syyx.com/news/js/topnews/0/34.htm',
    index_news_list_3       : 'http://att.syyx.com/news/js/topnews/0/33.htm',
    index_news_list_4       : 'http://att.syyx.com/news/js/topnews/0/35.htm',

    screenshot        : 'http://att.syyx.com/XGame/StaticHtml/12.htm',
    wallpaper         : 'http://att.syyx.com/XGame/StaticHtml/11.htm',
    cartoon           : 'http://att.syyx.com/XGame/StaticHtml/10.htm',
    video             : 'http://att.syyx.com/XGame/StaticHtml/9.htm',

    game_lib_nav      : 'http://att.syyx.com/XGame/StaticHtml/8.htm',
    game_lib_gameplay : 'http://att.syyx.com/XGame/StaticHtml/7.htm',

    get_hot_video     : 'http://nycs.syyx.com/Ajax/Video/GetHotVideo.aspx',
    get_user_video    : 'http://nycs.syyx.com/Ajax/Video/GetUserVideo.aspx',
    get_new_video     : 'http://nycs.syyx.com/Ajax/Video/GetNewVideo.aspx',
    get_video_info    : 'http://nycs.syyx.com/Ajax/Video/GetVideoInfo.aspx',

    screen_info    : 'http://nycs.syyx.com/Ajax/Pic/GetGamePic.aspx',
    wallpaper_info : 'http://nycs.syyx.com/Ajax/Pic/GetWallpaper.aspx',
    wallpaper_size : 'http://nycs.syyx.com/Ajax/Pic/GetOtherSize.aspx',

    check_login  : 'http://nycs.syyx.com/Ajax/Users/checkLogin.aspx',
    get_usercenter_list  : 'http://nycs.syyx.com/UserCenter/GetListByID.aspx',

    user_center_data  : 'http://nycs.syyx.com/UserCenter/GetListByID.aspx',
    user_center_data2 : 'http://nycs.syyx.com/UserCenter/GetList23.aspx',
    get_user_vote     : 'http://nycs.syyx.com/UserCenter/GetVoteData.aspx',
    set_user_vote     : 'http://nycs.syyx.com/UserCenter/SetVote.aspx'
}